In [1]:
from combinations import bounded_compositions, contingency_table, check_lex_order_for, deal_variants,\
generate_suit_size_distributions
import numpy as np
from tqdm import tqdm
import psycopg2

Генератор для перебора всех возможных распределений размеров мастей при следующих условиях:
* размер колоды $\texttt{deck}\_\texttt{size}=32$;
* размер масти $\texttt{max}\_\texttt{suit}\_\texttt{size}=8$;
* количество мастей $\texttt{max}\_\texttt{suits}=4$.

In [2]:
def generate_suit_sizes(predicate, max_suits=4, max_suit_size=8, deck_size=32):
    for n_cards in range(1, deck_size + 1):
        for n_suits in range(1, max_suits + 1):
            for suit_sizes in bounded_compositions(n_cards, n_suits, n_suits * [max_suit_size, ]):
                if predicate(suit_sizes):
                    yield suit_sizes.tolist()

Для преферанса получается $4680$ вариантов:

In [3]:
sorted_pref_suit_sizes = sorted(generate_suit_sizes(lambda s: s.min() > 0), key=lambda item: [len(item),] + item)
len(sorted_pref_suit_sizes)

4680

In [5]:
pref_stage_suit_sizes = []
for h in range(1, 11):
    for s in generate_suit_size_distributions(3*[h,], trump_idx=0):
        if s[1:].sum() > 0:
            pref_stage_suit_sizes.append(np.copy(s))
len(pref_stage_suit_sizes)

436

In [6]:
pref_stage_suit_sizes

[array([2, 0, 0, 1]),
 array([1, 0, 1, 1]),
 array([1, 0, 0, 2]),
 array([5, 0, 0, 1]),
 array([4, 0, 1, 1]),
 array([3, 1, 1, 1]),
 array([4, 0, 0, 2]),
 array([3, 0, 1, 2]),
 array([2, 1, 1, 2]),
 array([2, 0, 2, 2]),
 array([1, 1, 2, 2]),
 array([3, 0, 0, 3]),
 array([2, 0, 1, 3]),
 array([1, 1, 1, 3]),
 array([1, 0, 2, 3]),
 array([2, 0, 0, 4]),
 array([1, 0, 1, 4]),
 array([1, 0, 0, 5]),
 array([8, 0, 0, 1]),
 array([7, 0, 1, 1]),
 array([6, 1, 1, 1]),
 array([7, 0, 0, 2]),
 array([6, 0, 1, 2]),
 array([5, 1, 1, 2]),
 array([5, 0, 2, 2]),
 array([4, 1, 2, 2]),
 array([3, 2, 2, 2]),
 array([6, 0, 0, 3]),
 array([5, 0, 1, 3]),
 array([4, 1, 1, 3]),
 array([4, 0, 2, 3]),
 array([3, 1, 2, 3]),
 array([2, 2, 2, 3]),
 array([3, 0, 3, 3]),
 array([2, 1, 3, 3]),
 array([1, 2, 3, 3]),
 array([5, 0, 0, 4]),
 array([4, 0, 1, 4]),
 array([3, 1, 1, 4]),
 array([3, 0, 2, 4]),
 array([2, 1, 2, 4]),
 array([1, 2, 2, 4]),
 array([2, 0, 3, 4]),
 array([1, 1, 3, 4]),
 array([1, 0, 4, 4]),
 array([4,

Теперь надо их сохранить в базе данных.

In [6]:
def create_suit_sizes_table(cursor):
    query = '''
                CREATE TABLE IF NOT EXISTS suit_sizes_v3 (
                    index               SERIAL2 PRIMARY KEY,
                    deck_size           int2 NOT NULL CHECK (deck_size <= 32),
                    sizes          uint1[4]
            );
            '''
    cursor.execute(query)
    
def execute_suit_sizes_query(cursor, suit_sizes):
    query = "INSERT INTO suit_sizes_v3 (deck_size, sizes) VALUES (%s, %s);"
    cursor.execute(query, (sum(suit_sizes), [int(suit_size) for  suit_size in suit_sizes]))

def create_and_fill_suit_sizes_table():
    with psycopg2.connect('postgres://rafael:VfPLiCASXsMd7Y@localhost/preferance') as conn:
        with conn.cursor() as cur:
            create_suit_sizes_table(cur)
            for suit_sizes in sorted_pref_suit_sizes:
                execute_suit_sizes_query(cur, suit_sizes)
            conn.commit()

In [17]:
%%time
create_and_fill_suit_sizes_table()

CPU times: user 137 ms, sys: 82.3 ms, total: 219 ms
Wall time: 601 ms


Сумма размеров мастей в начале каждого этапа должна делиться на $3$, это даёт $1560$ вариантов.

In [4]:
suit_sizes_by_stage = sorted(generate_suit_sizes(lambda s: s.min() > 0 and s.sum() % 3 == 0),
                             key=lambda item: [len(item),] + item)
len(suit_sizes_by_stage)

1560

Ну а если отсортировать некозырные масти в порядке возрастания их размеров, получается хорошо известное число $438$ :-)

In [5]:
suit_sizes_by_stage_sorted = sorted(
    generate_suit_sizes(lambda s: s.min() > 0 and s.sum() % 3 == 0 and np.all(s[1:-1] <= s[2:])),
    key=lambda item: [len(item),] + item
)
len(suit_sizes_by_stage_sorted)

438

С целью экономии ограничимся хранением факторных матриц, соответствующих этим $438$ вариантам сумм столбцов.

In [9]:
def generate_contingency_tables(predicate, suit_sizes, n_hands=3):
    deck_size = sum(suit_sizes)
    hand_sizes = deck_size // n_hands * np.ones(n_hands, dtype=np.int8)
    hand_sizes[n_hands - deck_size%n_hands:] += 1
    for table in contingency_table(suit_sizes, hand_sizes):
        if len(table.shape) == 1:
            table = table[None, :]
        if predicate(suit_sizes, table):
            yield table

def rows_are_sorted(suit_sizes, table):
    for i in range(1, table.shape[0] - 1):
        if suit_sizes[i] == suit_sizes[i + 1] and not check_lex_order_for(table[i], table[i + 1]):
            return False
    return True

In [11]:
table_counts = []
for suit_sizes in tqdm(suit_sizes_by_stage_sorted):
    table_counts.append(len(list(generate_contingency_tables(rows_are_sorted, suit_sizes))))

100%|█████████████████████████████████████████| 438/438 [00:19<00:00, 22.60it/s]


In [59]:
sum(table_counts)

564020

Остаётся засунуть все эти $564020$ матриц в базу данных.

In [84]:
def create_contingency_table(cursor):
    query = f'''
                CREATE TABLE IF NOT EXISTS contingency_tables (
                    index               SERIAL PRIMARY KEY,
                    suit_sizes          int2 REFERENCES suit_sizes_v3,
                    matrix              uint1[][] NOT NULL
            );
            '''
    cursor.execute(query)
    
def get_suit_sizes_clause(suit_sizes):
    result = [f"deck_size = {sum(suit_sizes)}",]
    for i in range(1, len(suit_sizes) + 1):
        result.append(f"sizes[{i}] = %s") 
    return " AND ".join(result)

def execute_contingency_table_query(cursor, suit_sizes, table):
    query = f'''
        INSERT INTO contingency_tables (suit_sizes, matrix)
        VALUES ((SELECT index FROM suit_sizes_v3 WHERE {get_suit_sizes_clause(suit_sizes)}), %s);
    '''
    cursor.execute(query, (*suit_sizes, table.tolist()))
    
def create_and_fill_contingency_tables():
    with psycopg2.connect('postgres://rafael:VfPLiCASXsMd7Y@localhost/preferance') as conn:
        with conn.cursor() as cur:
            create_contingency_table(cur)
            for suit_sizes in tqdm(suit_sizes_by_stage_sorted):
                for table in generate_contingency_tables(rows_are_sorted, suit_sizes):
                    execute_contingency_table_query(cur, suit_sizes, table)
                conn.commit()

In [85]:
create_and_fill_contingency_tables()

100%|█████████████████████████████████████████| 438/438 [05:50<00:00,  1.25it/s]


In [90]:
%%time
res = None
with psycopg2.connect('postgres://rafael:VfPLiCASXsMd7Y@localhost/preferance') as conn:
    with conn.cursor() as cur:
        query = "SELECT * FROM contingency_tables WHERE suit_sizes > 4000"
        cur.execute(query)
        res = cur.fetchall()
print(len(res))

157788
CPU times: user 96.3 ms, sys: 32.7 ms, total: 129 ms
Wall time: 320 ms


In [24]:
suit_sizes_by_stage_sorted

[[3],
 [6],
 [1, 2],
 [1, 5],
 [1, 8],
 [2, 1],
 [2, 4],
 [2, 7],
 [3, 3],
 [3, 6],
 [4, 2],
 [4, 5],
 [4, 8],
 [5, 1],
 [5, 4],
 [5, 7],
 [6, 3],
 [6, 6],
 [7, 2],
 [7, 5],
 [7, 8],
 [8, 1],
 [8, 4],
 [8, 7],
 [1, 1, 1],
 [1, 1, 4],
 [1, 1, 7],
 [1, 2, 3],
 [1, 2, 6],
 [1, 3, 5],
 [1, 3, 8],
 [1, 4, 4],
 [1, 4, 7],
 [1, 5, 6],
 [1, 6, 8],
 [1, 7, 7],
 [2, 1, 3],
 [2, 1, 6],
 [2, 2, 2],
 [2, 2, 5],
 [2, 2, 8],
 [2, 3, 4],
 [2, 3, 7],
 [2, 4, 6],
 [2, 5, 5],
 [2, 5, 8],
 [2, 6, 7],
 [2, 8, 8],
 [3, 1, 2],
 [3, 1, 5],
 [3, 1, 8],
 [3, 2, 4],
 [3, 2, 7],
 [3, 3, 3],
 [3, 3, 6],
 [3, 4, 5],
 [3, 4, 8],
 [3, 5, 7],
 [3, 6, 6],
 [3, 7, 8],
 [4, 1, 1],
 [4, 1, 4],
 [4, 1, 7],
 [4, 2, 3],
 [4, 2, 6],
 [4, 3, 5],
 [4, 3, 8],
 [4, 4, 4],
 [4, 4, 7],
 [4, 5, 6],
 [4, 6, 8],
 [4, 7, 7],
 [5, 1, 3],
 [5, 1, 6],
 [5, 2, 2],
 [5, 2, 5],
 [5, 2, 8],
 [5, 3, 4],
 [5, 3, 7],
 [5, 4, 6],
 [5, 5, 5],
 [5, 5, 8],
 [5, 6, 7],
 [5, 8, 8],
 [6, 1, 2],
 [6, 1, 5],
 [6, 1, 8],
 [6, 2, 4],
 [6, 2, 7],
 [6, 3, 3]

In [48]:
%%time
results_nt = np.zeros(10, dtype=np.int64)
results_trump = np.zeros(10, dtype=np.int64)
results_nt_reduced = np.zeros(10, dtype=np.int64)
results_trump_reduced = np.zeros(10, dtype=np.int64)
nt_count = np.zeros(10, dtype=np.int32)
trump_count = np.zeros(10, dtype=np.int32)
for suit_sizes in suit_sizes_by_stage_sorted:
    stage = sum(suit_sizes) // 3 - 1
    for table in generate_contingency_tables(rows_are_sorted, suit_sizes):
        msg = ""
        if len(suit_sizes) == 1 or suit_sizes[0] < suit_sizes[1] or \
            (suit_sizes[0] == suit_sizes[1] and check_lex_order_for(table[0], table[1])):
            variants = deal_variants(table)
            variants_reduced = deal_variants(table, reduce=True)
            if variants != variants_reduced:
                msg += f"NT: {variants}, {variants_reduced}, "
            results_nt[stage] += variants
            results_nt_reduced[stage] += variants_reduced
            nt_count[stage] += 1
        
        if len(suit_sizes) > 1:
            variants = deal_variants(table, trump=True)
            variants_reduced = deal_variants(table, True, True)
            if variants != variants_reduced:
                msg += f"Trump: {variants}, {variants_reduced}"
            results_trump[stage] += variants
            results_trump_reduced[stage] += variants_reduced
            trump_count[stage] += 1
        if msg:
            print(msg)

NT: 36, 21, 
NT: 8100, 4095, 
Trump: 4, 3
NT: 4, 3, Trump: 4, 3
NT: 4, 3, 
NT: 4, 3, Trump: 4, 3
NT: 80, 60, 
NT: 80, 60, 
NT: 80, 60, 
NT: 1680, 1260, 
NT: 1680, 1260, 
NT: 1680, 1260, 
NT: 900, 465, Trump: 900, 465
NT: 900, 465, Trump: 900, 465
NT: 900, 465, Trump: 900, 465
NT: 313600, 157080, Trump: 313600, 157080
NT: 313600, 157080, Trump: 313600, 157080
NT: 313600, 157080, Trump: 313600, 157080
NT: 216, 56, Trump: 216, 126
NT: 135, 90, 
NT: 135, 90, 
NT: 135, 90, 
NT: 3240, 1890, 
NT: 135, 90, 
NT: 135, 90, 
NT: 135, 90, 
NT: 48600, 24570, Trump: 48600, 24570
Trump: 36, 21
Trump: 864, 468
NT: 36, 21, Trump: 36, 21
NT: 864, 468, 
Trump: 864, 468
NT: 864, 468, 
NT: 864, 468, Trump: 864, 468
NT: 36, 21, 
NT: 36, 21, Trump: 36, 21
NT: 1512, 882, 
NT: 20160, 10920, 
NT: 20160, 10920, 
NT: 1512, 882, 
NT: 20160, 10920, 
NT: 1512, 882, 
NT: 19600, 9870, Trump: 19600, 9870
NT: 264600, 132930, Trump: 264600, 132930
NT: 19600, 9870, Trump: 19600, 9870
NT: 264600, 132930, Trump: 264600, 1329

NT: 700, 385, Trump: 700, 385
NT: 94500, 48825, Trump: 94500, 48825
NT: 94500, 48825, Trump: 94500, 48825
NT: 700, 385, Trump: 700, 385
NT: 400, 210, Trump: 400, 210
NT: 36000, 18300, Trump: 36000, 18300
NT: 18000, 9150, Trump: 18000, 9150
NT: 36000, 18300, Trump: 36000, 18300
NT: 243000, 122850, Trump: 243000, 122850
NT: 18000, 9150, Trump: 18000, 9150
NT: 18000, 9150, Trump: 18000, 9150
NT: 36000, 18300, Trump: 36000, 18300
NT: 400, 210, Trump: 400, 210
NT: 243000, 122850, Trump: 243000, 122850
NT: 36000, 18300, Trump: 36000, 18300
NT: 18000, 9150, Trump: 18000, 9150
NT: 18000, 9150, Trump: 18000, 9150
NT: 243000, 122850, Trump: 243000, 122850
NT: 18000, 9150, Trump: 18000, 9150
NT: 36000, 18300, Trump: 36000, 18300
NT: 36000, 18300, Trump: 36000, 18300
NT: 400, 210, Trump: 400, 210
NT: 3200, 1680, Trump: 3200, 1680
NT: 201600, 102480, Trump: 201600, 102480
NT: 604800, 307440, Trump: 604800, 307440
NT: 201600, 102480, Trump: 201600, 102480
NT: 4536000, 2293200, Trump: 4536000, 229320

NT: 19600, 9870, Trump: 19600, 9870
Trump: 44100, 22155
Trump: 44100, 22155
NT: 14700, 11025, 
NT: 176400, 66465, Trump: 176400, 88620
NT: 78400, 58800, 
NT: 4900, 3675, 
NT: 88200, 66150, 
NT: 88200, 66150, 
NT: 14700, 11025, 
NT: 8820, 6615, 
NT: 23520, 17640, 
NT: 8820, 6615, 
NT: 980, 735, 
NT: 980, 735, 
NT: 44100, 22155, Trump: 44100, 22155
NT: 19600, 9870, Trump: 19600, 9870
Trump: 44100, 22155
NT: 980, 735, 
NT: 23520, 17640, 
NT: 980, 735, 
NT: 176400, 66465, Trump: 176400, 88620
NT: 88200, 66150, 
NT: 8820, 6615, 
NT: 88200, 66150, 
NT: 78400, 58800, 
NT: 14700, 11025, 
NT: 8820, 6615, 
NT: 14700, 11025, 
NT: 4900, 3675, 
NT: 14700, 11025, 
NT: 176400, 66465, Trump: 176400, 88620
NT: 88200, 66150, 
NT: 8820, 6615, 
NT: 78400, 58800, 
NT: 88200, 66150, 
NT: 23520, 17640, 
NT: 980, 735, 
NT: 4900, 3675, 
NT: 14700, 11025, 
NT: 8820, 6615, 
NT: 980, 735, 
NT: 44100, 22155, Trump: 44100, 22155
NT: 44100, 22155, Trump: 44100, 22155
NT: 19600, 9870, Trump: 19600, 9870
NT: 9, 6, Tru

NT: 54000, 27900, Trump: 54000, 27900
NT: 108000, 55800, Trump: 108000, 55800
NT: 1200, 660, Trump: 1200, 660
NT: 1200, 660, Trump: 1200, 660
NT: 16000, 8400, Trump: 16000, 8400
NT: 108000, 55800, Trump: 108000, 55800
NT: 1200, 660, Trump: 1200, 660
NT: 108000, 55800, Trump: 108000, 55800
NT: 54000, 27900, Trump: 54000, 27900
NT: 1500, 825, Trump: 1500, 825
NT: 1500, 825, Trump: 1500, 825
NT: 6000, 3150, Trump: 6000, 3150
NT: 81000, 41850, Trump: 81000, 41850
NT: 6000, 3150, Trump: 6000, 3150
NT: 100, 55, Trump: 100, 55
NT: 13500, 6975, Trump: 13500, 6975
NT: 13500, 6975, Trump: 13500, 6975
NT: 100, 55, Trump: 100, 55
NT: 392000, 197400, Trump: 392000, 197400
NT: 882000, 443100, Trump: 882000, 443100
NT: 882000, 443100, Trump: 882000, 443100
NT: 196000, 98700, Trump: 196000, 98700
NT: 2646000, 1329300, Trump: 2646000, 1329300
NT: 196000, 98700, Trump: 196000, 98700
NT: 882000, 443100, Trump: 882000, 443100
NT: 882000, 443100, Trump: 882000, 443100
NT: 39200, 19740, Trump: 39200, 19740


NT: 308700, 155820, Trump: 308700, 155820
NT: 1225, 630, Trump: 1225, 630
NT: 548800, 276360, Trump: 548800, 276360
NT: 3087000, 1550850, Trump: 3087000, 1550850
NT: 548800, 276360, Trump: 548800, 276360
NT: 1225, 630, Trump: 1225, 630
Trump: 36, 21
Trump: 432, 234
Trump: 432, 234
Trump: 36, 21
Trump: 432, 234
Trump: 432, 234
Trump: 432, 234
Trump: 432, 234
Trump: 36, 21
Trump: 19600, 9870
Trump: 132300, 66465
Trump: 132300, 66465
Trump: 19600, 9870
Trump: 132300, 66465
Trump: 132300, 66465
Trump: 132300, 66465
Trump: 132300, 66465
Trump: 19600, 9870
Trump: 8, 4
Trump: 24, 18
Trump: 24, 18
Trump: 8, 4
Trump: 24, 18
Trump: 24, 18
Trump: 24, 18
Trump: 24, 18
Trump: 24, 18
Trump: 24, 18
Trump: 24, 18
Trump: 8, 4
Trump: 120, 90
Trump: 60, 45
Trump: 120, 90
Trump: 360, 270
Trump: 60, 45
Trump: 360, 270
Trump: 120, 90
Trump: 120, 90
Trump: 120, 90
Trump: 60, 45
Trump: 360, 270
Trump: 480, 360
Trump: 480, 360
Trump: 480, 360
Trump: 120, 90
Trump: 360, 270
Trump: 60, 45
Trump: 360, 270
Trump: 

NT: 945, 630, 
NT: 9450, 6300, 
NT: 18900, 12600, 
NT: 9450, 6300, 
NT: 945, 630, 
NT: 4725, 3150, 
NT: 25200, 16800, 
NT: 28350, 18900, 
NT: 7560, 5040, 
NT: 315, 210, 
NT: 3150, 2100, 
NT: 9450, 6300, 
NT: 5670, 3780, 
NT: 630, 420, 
NT: 400, 210, Trump: 400, 210
Trump: 10800, 5490
Trump: 10800, 5490
NT: 2025, 1350, 
NT: 32400, 10980, Trump: 32400, 16470
NT: 10800, 7200, 
NT: 16200, 10800, 
NT: 12150, 8100, 
NT: 1620, 1080, 
NT: 3240, 2160, 
NT: 135, 90, 
Trump: 10800, 5490
Trump: 72900, 36855
NT: 10800, 5490, Trump: 10800, 5490
NT: 32400, 10980, Trump: 32400, 16470
NT: 10800, 7200, 
NT: 12150, 8100, 
NT: 16200, 10800, 
NT: 2025, 1350, 
NT: 3240, 2160, 
NT: 1620, 1080, 
NT: 135, 90, 
Trump: 72900, 36855
NT: 10800, 5490, Trump: 10800, 5490
NT: 400, 210, Trump: 400, 210
Trump: 10800, 5490
NT: 135, 90, 
NT: 3240, 2160, 
NT: 32400, 10980, Trump: 32400, 16470
NT: 12150, 8100, 
NT: 16200, 10800, 
NT: 10800, 7200, 
NT: 1620, 1080, 
NT: 2025, 1350, 
Trump: 72900, 36855
Trump: 10800, 5490
NT:

NT: 235200, 118440, Trump: 235200, 118440
NT: 176400, 88620, Trump: 176400, 88620
NT: 176400, 88620, Trump: 176400, 88620
NT: 235200, 118440, Trump: 235200, 118440
NT: 1587600, 797580, Trump: 1587600, 797580
NT: 529200, 265860, Trump: 529200, 265860
NT: 1587600, 797580, Trump: 1587600, 797580
NT: 235200, 118440, Trump: 235200, 118440
NT: 529200, 265860, Trump: 529200, 265860
NT: 176400, 88620, Trump: 176400, 88620
NT: 235200, 118440, Trump: 235200, 118440
NT: 176400, 88620, Trump: 176400, 88620
NT: 235200, 118440, Trump: 235200, 118440
NT: 529200, 265860, Trump: 529200, 265860
NT: 1587600, 797580, Trump: 1587600, 797580
NT: 117600, 59220, Trump: 117600, 59220
NT: 1587600, 797580, Trump: 1587600, 797580
NT: 117600, 59220, Trump: 117600, 59220
NT: 1587600, 797580, Trump: 1587600, 797580
NT: 1587600, 797580, Trump: 1587600, 797580
NT: 117600, 59220, Trump: 117600, 59220
NT: 529200, 265860, Trump: 529200, 265860
NT: 235200, 118440, Trump: 235200, 118440
NT: 1587600, 797580, Trump: 1587600,

NT: 28224000, 14137200, Trump: 28224000, 14137200
NT: 1176000, 590100, Trump: 1176000, 590100
NT: 9408000, 4712400, Trump: 9408000, 4712400
NT: 5292000, 2652300, Trump: 5292000, 2652300
NT: 235200, 118020, Trump: 235200, 118020
NT: 235200, 118020, Trump: 235200, 118020
NT: 9408000, 4712400, Trump: 9408000, 4712400
NT: 4704000, 2356200, Trump: 4704000, 2356200
NT: 5292000, 2652300, Trump: 5292000, 2652300
NT: 28224000, 14137200, Trump: 28224000, 14137200
NT: 1176000, 590100, Trump: 1176000, 590100
NT: 4704000, 2356200, Trump: 4704000, 2356200
NT: 9408000, 4712400, Trump: 9408000, 4712400
NT: 235200, 118020, Trump: 235200, 118020
NT: 28224000, 14137200, Trump: 28224000, 14137200
NT: 5292000, 2652300, Trump: 5292000, 2652300
NT: 1176000, 590100, Trump: 1176000, 590100
NT: 882000, 442050, Trump: 882000, 442050
NT: 9408000, 4712400, Trump: 9408000, 4712400
NT: 882000, 442050, Trump: 882000, 442050
NT: 784000, 393400, Trump: 784000, 393400
NT: 784000, 393400, Trump: 784000, 393400
NT: 4900, 

NT: 526848000, 263894400, Trump: 526848000, 263894400
NT: 263424000, 131947200, Trump: 263424000, 131947200
NT: 13171200, 6609120, Trump: 13171200, 6609120
NT: 148176000, 74264400, Trump: 148176000, 74264400
NT: 13171200, 6609120, Trump: 13171200, 6609120
NT: 158054400, 79168320, Trump: 158054400, 79168320
NT: 29635200, 14852880, Trump: 29635200, 14852880
NT: 1881600, 944160, Trump: 1881600, 944160
NT: 274400, 139160, Trump: 274400, 139160
NT: 175616000, 29426320, Trump: 175616000, 29426320
NT: 17561600, 8796480, Trump: 17561600, 8796480
NT: 21952000, 11015200, Trump: 21952000, 11015200
NT: 21952000, 11015200, Trump: 21952000, 11015200
NT: 29635200, 14852880, Trump: 29635200, 14852880
NT: 627200, 314720, Trump: 627200, 314720
NT: 17561600, 8796480, Trump: 17561600, 8796480
NT: 29635200, 14852880, Trump: 29635200, 14852880
NT: 627200, 314720, Trump: 627200, 314720
NT: 1881600, 944160, Trump: 1881600, 944160
NT: 148176000, 74264400, Trump: 148176000, 74264400
NT: 158054400, 79168320, Tru

Trump: 18144, 12096
Trump: 6048, 4032
Trump: 30240, 20160
Trump: 241920, 141120
Trump: 6048, 4032
Trump: 30240, 20160
Trump: 18144, 12096
Trump: 6048, 4032
Trump: 20160, 13440
Trump: 40320, 23520
Trump: 10080, 6720
Trump: 2016, 1344
Trump: 3780, 2520
Trump: 22680, 15120
Trump: 1512, 1008
Trump: 90720, 52920
Trump: 22680, 15120
Trump: 1512, 1008
Trump: 3780, 2520
Trump: 30240, 20160
Trump: 30240, 20160
Trump: 18144, 12096
Trump: 241920, 141120
Trump: 18144, 12096
Trump: 6048, 4032
Trump: 6048, 4032
Trump: 22680, 15120
Trump: 3780, 2520
Trump: 22680, 15120
Trump: 90720, 52920
Trump: 1512, 1008
Trump: 3780, 2520
Trump: 1512, 1008
Trump: 10080, 6720
Trump: 20160, 13440
Trump: 2016, 1344
Trump: 40320, 23520
Trump: 6048, 4032
Trump: 20160, 13440
Trump: 10080, 6720
Trump: 6048, 4032
Trump: 40320, 23520
Trump: 2016, 1344
Trump: 3780, 2520
Trump: 3780, 2520
Trump: 252, 168
Trump: 2520, 1470
Trump: 252, 168
Trump: 216, 126
Trump: 432, 252
Trump: 1728, 936
Trump: 576, 312
Trump: 5184, 2808
Trump:

NT: 4480, 2800, 
NT: 2688, 1680, 
NT: 22400, 14000, 
NT: 22400, 14000, 
NT: 26880, 16800, 
NT: 44800, 28000, 
NT: 8960, 5600, 
NT: 26880, 16800, 
NT: 640, 400, 
NT: 4480, 2800, 
NT: 128, 80, 
NT: 80640, 43680, 
NT: 241920, 131040, 
NT: 120960, 65520, 
NT: 8064, 4368, 
NT: 201600, 109200, 
NT: 1209600, 655200, 
NT: 1209600, 655200, 
NT: 201600, 109200, 
NT: 80640, 43680, 
NT: 1209600, 655200, 
NT: 2419200, 1310400, 
NT: 806400, 436800, 
NT: 241920, 131040, 
NT: 1209600, 655200, 
NT: 806400, 436800, 
NT: 120960, 65520, 
NT: 201600, 109200, 
NT: 8064, 4368, 
NT: 8064, 4368, 
NT: 120960, 65520, 
NT: 241920, 131040, 
NT: 80640, 43680, 
NT: 201600, 109200, 
NT: 1209600, 655200, 
NT: 1209600, 655200, 
NT: 201600, 109200, 
NT: 806400, 436800, 
NT: 2419200, 1310400, 
NT: 1209600, 655200, 
NT: 80640, 43680, 
NT: 806400, 436800, 
NT: 1209600, 655200, 
NT: 241920, 131040, 
NT: 201600, 109200, 
NT: 120960, 65520, 
NT: 8064, 4368, 
NT: 2688, 1680, 
NT: 4480, 2800, 
NT: 22400, 14000, 
NT: 22400, 1400

NT: 80640, 47040, 
NT: 2520, 1470, 
NT: 1128960, 658560, 
NT: 80640, 47040, 
NT: 6350400, 1856610, Trump: 6350400, 3182760
NT: 3386880, 1975680, 
NT: 423360, 246960, 
NT: 3386880, 1975680, 
NT: 2822400, 1646400, 
NT: 564480, 329280, 
NT: 423360, 246960, 
NT: 564480, 329280, 
NT: 176400, 102900, 
Trump: 11289600, 5654880
Trump: 470400, 236040
NT: 15052800, 7539840, Trump: 15052800, 7539840
NT: 15052800, 7539840, Trump: 15052800, 7539840
NT: 282240, 152880, 
NT: 6773760, 3669120, 
NT: 451584, 244608, 
NT: 45158400, 12252240, Trump: 45158400, 22619520
NT: 25401600, 13759200, 
NT: 4064256, 2201472, 
NT: 112896, 61152, 
NT: 22579200, 12230400, 
NT: 22579200, 12230400, 
NT: 6773760, 3669120, 
NT: 451584, 244608, 
NT: 2257920, 1223040, 
NT: 4233600, 2293200, 
NT: 2257920, 1223040, 
NT: 282240, 152880, 
NT: 1881600, 942480, Trump: 1881600, 942480
NT: 11289600, 5654880, Trump: 11289600, 5654880
NT: 470400, 236040, Trump: 470400, 236040
NT: 11289600, 5654880, Trump: 11289600, 5654880
NT: 564480,

NT: 216000, 109800, Trump: 216000, 109800
NT: 2916000, 1474200, Trump: 2916000, 1474200
NT: 216000, 109800, Trump: 216000, 109800
NT: 432000, 219600, Trump: 432000, 219600
NT: 432000, 219600, Trump: 432000, 219600
NT: 4800, 2520, Trump: 4800, 2520
NT: 972000, 491400, Trump: 972000, 491400
NT: 432000, 219600, Trump: 432000, 219600
NT: 432000, 219600, Trump: 432000, 219600
NT: 72000, 36600, Trump: 72000, 36600
NT: 324000, 163800, Trump: 324000, 163800
NT: 14400, 7320, Trump: 14400, 7320
NT: 432000, 219600, Trump: 432000, 219600
NT: 144000, 73200, Trump: 144000, 73200
NT: 8000, 4200, Trump: 8000, 4200
NT: 14400, 7320, Trump: 14400, 7320
NT: 324000, 163800, Trump: 324000, 163800
NT: 72000, 36600, Trump: 72000, 36600
NT: 144000, 73200, Trump: 144000, 73200
NT: 432000, 219600, Trump: 432000, 219600
NT: 8000, 4200, Trump: 8000, 4200
NT: 72000, 36600, Trump: 72000, 36600
NT: 72000, 36600, Trump: 72000, 36600
NT: 8000, 4200, Trump: 8000, 4200
NT: 225, 120, Trump: 225, 120
NT: 100800, 51240, Tru

NT: 882000, 445200, Trump: 882000, 445200
NT: 29400, 15120, Trump: 29400, 15120
NT: 10584000, 5317200, Trump: 10584000, 5317200
NT: 4704000, 2368800, Trump: 4704000, 2368800
NT: 5292000, 2658600, Trump: 5292000, 2658600
NT: 11025, 5565, Trump: 11025, 5565
NT: 165375, 83475, Trump: 165375, 83475
NT: 18375, 9450, Trump: 18375, 9450
NT: 661500, 332325, Trump: 661500, 332325
NT: 1764000, 888300, Trump: 1764000, 888300
NT: 18375, 9450, Trump: 18375, 9450
NT: 661500, 332325, Trump: 661500, 332325
NT: 165375, 83475, Trump: 165375, 83475
NT: 11025, 5565, Trump: 11025, 5565
NT: 29400, 15120, Trump: 29400, 15120
NT: 4704000, 2368800, Trump: 4704000, 2368800
NT: 5292000, 2658600, Trump: 5292000, 2658600
NT: 882000, 445200, Trump: 882000, 445200
NT: 10584000, 5317200, Trump: 10584000, 5317200
NT: 264600, 133560, Trump: 264600, 133560
NT: 7056000, 3553200, Trump: 7056000, 3553200
NT: 31752000, 15951600, Trump: 31752000, 15951600
NT: 1411200, 710640, Trump: 1411200, 710640
NT: 31752000, 15951600, Tr

NT: 79027200, 39584160, Trump: 79027200, 39584160
NT: 263424000, 131947200, Trump: 263424000, 131947200
NT: 19756800, 9913680, Trump: 19756800, 9913680
NT: 263424000, 131947200, Trump: 263424000, 131947200
NT: 148176000, 74264400, Trump: 148176000, 74264400
NT: 19756800, 9913680, Trump: 19756800, 9913680
NT: 2195200, 1101520, Trump: 2195200, 1101520
NT: 43904000, 21991200, Trump: 43904000, 21991200
NT: 26342400, 13194720, Trump: 26342400, 13194720
NT: 313600, 157360, Trump: 313600, 157360
NT: 74088000, 37132200, Trump: 74088000, 37132200
NT: 263424000, 131947200, Trump: 263424000, 131947200
NT: 14817600, 7426440, Trump: 14817600, 7426440
NT: 32928000, 16522800, Trump: 32928000, 16522800
NT: 10976000, 5507600, Trump: 10976000, 5507600
NT: 137200, 69580, Trump: 137200, 69580
NT: 313600, 157360, Trump: 313600, 157360
NT: 26342400, 13194720, Trump: 26342400, 13194720
NT: 43904000, 21991200, Trump: 43904000, 21991200
NT: 2195200, 1101520, Trump: 2195200, 1101520
NT: 14817600, 7426440, Trump

Trump: 1176000, 590100
Trump: 4704000, 2356200
Trump: 882000, 442050
Trump: 37632000, 18849600
Trump: 28224000, 14137200
Trump: 28224000, 14137200
Trump: 9408000, 4712400
Trump: 37632000, 18849600
Trump: 4704000, 2356200
Trump: 1176000, 590100
Trump: 882000, 442050
Trump: 784000, 393400
Trump: 9408000, 4712400
Trump: 5292000, 2652300
Trump: 28224000, 14137200
Trump: 9408000, 4712400
Trump: 28224000, 14137200
Trump: 9408000, 4712400
Trump: 28224000, 14137200
Trump: 28224000, 14137200
Trump: 9408000, 4712400
Trump: 784000, 393400
Trump: 5292000, 2652300
Trump: 5292000, 2652300
Trump: 9408000, 4712400
Trump: 784000, 393400
Trump: 37632000, 18849600
Trump: 9408000, 4712400
Trump: 5292000, 2652300
Trump: 784000, 393400
Trump: 882000, 442050
Trump: 4704000, 2356200
Trump: 1176000, 590100
Trump: 4704000, 2356200
Trump: 882000, 442050
Trump: 1176000, 590100
Trump: 235200, 118020
Trump: 235200, 118020
Trump: 4900, 2485
Trump: 80, 50
Trump: 1080, 630
Trump: 80, 50
Trump: 3600, 1950
Trump: 7200, 

Trump: 120000, 63000
Trump: 270000, 139500
Trump: 1620000, 837000
Trump: 30000, 16500
Trump: 2000, 1100
Trump: 120000, 63000
Trump: 30000, 16500
NT: 54000, 27900, 
NT: 54000, 27900, 
NT: 270000, 139500, 
NT: 810000, 148800, Trump: 810000, 418500
NT: 180000, 93000, 
Trump: 1620000, 837000
Trump: 1620000, 837000
Trump: 18000, 9900
Trump: 240000, 126000
Trump: 18000, 9900
NT: 2000, 1100, Trump: 2000, 1100
NT: 120000, 63000, Trump: 120000, 63000
NT: 270000, 139500, Trump: 270000, 139500
NT: 2400, 1260, 
NT: 12000, 6300, 
NT: 60000, 31500, 
NT: 120000, 63000, 
NT: 240000, 126000, 
NT: 240000, 126000, 
NT: 240000, 126000, 
NT: 30000, 16500, Trump: 30000, 16500
NT: 1620000, 837000, Trump: 1620000, 837000
Trump: 270000, 139500
NT: 30000, 16500, Trump: 30000, 16500
Trump: 120000, 63000
Trump: 2000, 1100
NT: 60000, 31500, Trump: 60000, 31500
NT: 30000, 16500, Trump: 30000, 16500
NT: 270000, 139500, Trump: 270000, 139500
NT: 10000, 5500, Trump: 10000, 5500
NT: 12000, 6300, Trump: 12000, 6300
Trum

NT: 25, 15, 
NT: 1200, 720, 
NT: 10500, 6300, 
NT: 28000, 16800, 
NT: 26250, 15750, 
NT: 8400, 5040, 
NT: 700, 420, 
NT: 700, 420, 
NT: 8400, 5040, 
NT: 26250, 15750, 
NT: 28000, 16800, 
NT: 10500, 6300, 
NT: 1200, 720, 
NT: 25, 15, 
Trump: 12250, 6300
Trump: 55125, 27825
Trump: 12250, 6300
Trump: 588000, 296100
Trump: 55125, 27825
NT: 30625, 9450, Trump: 30625, 15750
NT: 18375, 11025, 
NT: 3675, 2205, 
NT: 175, 105, 
Trump: 551250, 278250
Trump: 55125, 27825
Trump: 2940000, 1480500
Trump: 2205000, 1107750
Trump: 1102500, 553875
NT: 12250, 6300, Trump: 12250, 6300
NT: 73500, 40425, 
NT: 1102500, 306075, Trump: 1102500, 556500
NT: 367500, 202125, 
NT: 588000, 323400, 
NT: 441000, 242550, 
NT: 73500, 40425, 
NT: 147000, 80850, 
NT: 10500, 5775, 
Trump: 551250, 278250
Trump: 1960000, 987000
Trump: 13230000, 6646500
Trump: 2205000, 1107750
NT: 551250, 278250, Trump: 551250, 278250
NT: 1102500, 306075, Trump: 1102500, 556500
NT: 367500, 202125, 
NT: 441000, 242550, 
NT: 588000, 323400, 
NT:

NT: 1417500, 716625, Trump: 1417500, 716625
NT: 3780000, 1921500, Trump: 3780000, 1921500
NT: 39375, 21000, Trump: 39375, 21000
NT: 126000, 64050, Trump: 126000, 64050
NT: 1890000, 960750, Trump: 1890000, 960750
NT: 210000, 110250, Trump: 210000, 110250
NT: 3024000, 1537200, Trump: 3024000, 1537200
NT: 22680000, 11466000, Trump: 22680000, 11466000
NT: 10080000, 5124000, Trump: 10080000, 5124000
NT: 3024000, 1537200, Trump: 3024000, 1537200
NT: 10080000, 5124000, Trump: 10080000, 5124000
NT: 336000, 176400, Trump: 336000, 176400
NT: 12000, 6300, Trump: 12000, 6300
NT: 2268000, 1152900, Trump: 2268000, 1152900
NT: 2268000, 1152900, Trump: 2268000, 1152900
NT: 3780000, 1921500, Trump: 3780000, 1921500
NT: 51030000, 25798500, Trump: 51030000, 25798500
NT: 3780000, 1921500, Trump: 3780000, 1921500
NT: 84000, 44100, Trump: 84000, 44100
NT: 11340000, 5764500, Trump: 11340000, 5764500
NT: 11340000, 5764500, Trump: 11340000, 5764500
NT: 84000, 44100, Trump: 84000, 44100
NT: 3024000, 1537200, Tr

NT: 94080000, 47124000, Trump: 94080000, 47124000
NT: 23520000, 11802000, Trump: 23520000, 11802000
NT: 26460000, 13261500, Trump: 26460000, 13261500
NT: 23520000, 11802000, Trump: 23520000, 11802000
NT: 188160000, 94248000, Trump: 188160000, 94248000
NT: 18816000, 9424800, Trump: 18816000, 9424800
NT: 105840000, 53046000, Trump: 105840000, 53046000
NT: 62720000, 31416000, Trump: 62720000, 31416000
NT: 4704000, 2360400, Trump: 4704000, 2360400
NT: 14112000, 7081200, Trump: 14112000, 7081200
NT: 564480000, 282744000, Trump: 564480000, 282744000
NT: 282240000, 141372000, Trump: 282240000, 141372000
NT: 105840000, 53046000, Trump: 105840000, 53046000
NT: 564480000, 282744000, Trump: 564480000, 282744000
NT: 14112000, 7081200, Trump: 14112000, 7081200
NT: 282240000, 141372000, Trump: 282240000, 141372000
NT: 564480000, 282744000, Trump: 564480000, 282744000
NT: 14112000, 7081200, Trump: 14112000, 7081200
NT: 564480000, 282744000, Trump: 564480000, 282744000
NT: 105840000, 53046000, Trump: 

NT: 441000, 222600, Trump: 441000, 222600
NT: 98000, 50400, Trump: 98000, 50400
NT: 10976000, 5527200, Trump: 10976000, 5527200
NT: 18522000, 9349200, Trump: 18522000, 9349200
NT: 24696000, 12406800, Trump: 24696000, 12406800
NT: 246960000, 124068000, Trump: 246960000, 124068000
NT: 30870000, 15582000, Trump: 30870000, 15582000
NT: 1568000, 789600, Trump: 1568000, 789600
NT: 74088000, 37220400, Trump: 74088000, 37220400
NT: 54880000, 27636000, Trump: 54880000, 27636000
NT: 686000, 352800, Trump: 686000, 352800
NT: 294000, 151200, Trump: 294000, 151200
NT: 98784000, 49744800, Trump: 98784000, 49744800
NT: 18522000, 9349200, Trump: 18522000, 9349200
NT: 370440000, 186102000, Trump: 370440000, 186102000
NT: 740880000, 372204000, Trump: 740880000, 372204000
NT: 18522000, 9349200, Trump: 18522000, 9349200
NT: 32928000, 16581600, Trump: 32928000, 16581600
NT: 370440000, 186102000, Trump: 370440000, 186102000
NT: 98784000, 49744800, Trump: 98784000, 49744800
NT: 294000, 151200, Trump: 294000,

Trump: 1200, 660
Trump: 100, 55
Trump: 100, 55
Trump: 4900, 2485
Trump: 78400, 39340
Trump: 78400, 39340
Trump: 940800, 472080
Trump: 1176000, 590100
Trump: 2646000, 1326150
Trump: 4704000, 2356200
Trump: 7056000, 3536400
Trump: 2646000, 1326150
Trump: 1176000, 590100
Trump: 4704000, 2356200
Trump: 940800, 472080
Trump: 78400, 39340
Trump: 4900, 2485
Trump: 78400, 39340
Trump: 940800, 472080
Trump: 18816000, 9424800
Trump: 37632000, 18849600
Trump: 37632000, 18849600
Trump: 18816000, 9424800
Trump: 940800, 472080
Trump: 1176000, 590100
Trump: 4704000, 2356200
Trump: 2646000, 1326150
Trump: 37632000, 18849600
Trump: 28224000, 14137200
Trump: 28224000, 14137200
Trump: 28224000, 14137200
Trump: 37632000, 18849600
Trump: 4704000, 2356200
Trump: 1176000, 590100
Trump: 2646000, 1326150
Trump: 7056000, 3536400
Trump: 37632000, 18849600
Trump: 37632000, 18849600
Trump: 7056000, 3536400
Trump: 2646000, 1326150
Trump: 4704000, 2356200
Trump: 1176000, 590100
Trump: 18816000, 9424800
Trump: 470400

Trump: 1814400, 982800
Trump: 1814400, 982800
Trump: 136080, 79380
Trump: 1814400, 982800
Trump: 136080, 79380
Trump: 20160, 12600
Trump: 45360, 26460
Trump: 33600, 21000
Trump: 1814400, 982800
Trump: 302400, 163800
Trump: 226800, 132300
Trump: 907200, 491400
Trump: 15120, 8820
Trump: 10080, 6300
Trump: 33600, 21000
Trump: 302400, 163800
Trump: 75600, 44100
Trump: 90720, 49140
Trump: 25200, 14700
Trump: 33600, 21000
Trump: 60480, 32760
Trump: 604800, 327600
Trump: 33600, 21000
Trump: 720, 420
Trump: 60480, 32760
Trump: 25200, 14700
Trump: 226800, 132300
Trump: 33600, 21000
Trump: 907200, 491400
Trump: 1814400, 982800
Trump: 20160, 12600
Trump: 15120, 8820
Trump: 302400, 163800
Trump: 45360, 26460
Trump: 33600, 21000
Trump: 226800, 132300
Trump: 20160, 12600
Trump: 1814400, 982800
Trump: 907200, 491400
Trump: 45360, 26460
Trump: 302400, 163800
Trump: 15120, 8820
Trump: 33600, 21000
Trump: 25200, 14700
Trump: 33600, 21000
Trump: 604800, 327600
Trump: 60480, 32760
Trump: 25200, 14700
Trum

Trump: 9072000, 4687200
Trump: 336000, 184800
Trump: 30240000, 15624000
Trump: 15120000, 7812000
Trump: 1008000, 554400
Trump: 6720000, 3528000
Trump: 336000, 184800
Trump: 24000, 13200
Trump: 2016000, 1058400
Trump: 1512000, 781200
Trump: 840000, 462000
Trump: 15120000, 7812000
Trump: 1512000, 781200
Trump: 840000, 462000
Trump: 2016000, 1058400
Trump: 24000, 13200
Trump: 1200, 720
Trump: 8400, 5040
Trump: 403200, 211680
Trump: 336000, 184800
Trump: 1512000, 781200
Trump: 168000, 92400
Trump: 134400, 70560
Trump: 42000, 23100
Trump: 10500, 6300
Trump: 945000, 488250
Trump: 2520000, 1323000
Trump: 26250, 15750
Trump: 378000, 195300
Trump: 5670000, 2929500
Trump: 630000, 346500
Trump: 1500, 825
Trump: 168000, 88200
Trump: 105000, 57750
Trump: 336000, 184800
Trump: 15120000, 7812000
Trump: 6720000, 3528000
Trump: 9072000, 4687200
Trump: 30240000, 15624000
Trump: 1008000, 554400
Trump: 48000, 26400
Trump: 1344000, 705600
Trump: 336000, 184800
Trump: 252000, 138600
Trump: 252000, 138600
Tr

Trump: 144000, 75600
Trump: 6480000, 3294000
Trump: 36000, 18900
NT: 65610000, 2919735, Trump: 65610000, 11302200
Trump: 4860000, 2470500
Trump: 4860000, 2470500
Trump: 4860000, 2470500
Trump: 4860000, 2470500
Trump: 36000, 18900
Trump: 4860000, 2470500
Trump: 4860000, 2470500
Trump: 36000, 18900
NT: 144000, 75600, Trump: 144000, 75600
NT: 29160000, 14742000, Trump: 29160000, 14742000
NT: 12960000, 3348900, Trump: 12960000, 6588000
NT: 4860000, 2470500, 
NT: 4320000, 2196000, 
NT: 6480000, 3294000, 
NT: 810000, 411750, 
NT: 4320000, 2196000, Trump: 4320000, 2196000
Trump: 1296000, 658800
Trump: 6480000, 3294000
NT: 90000, 47250, Trump: 90000, 47250
NT: 4860000, 2470500, Trump: 4860000, 2470500
NT: 1822500, 921375, Trump: 1822500, 921375
NT: 50625, 14400, Trump: 50625, 27000
NT: 27000, 14400, 
NT: 3375, 1800, 
NT: 810000, 411750, Trump: 810000, 411750
NT: 54000, 27450, Trump: 54000, 27450
NT: 810000, 411750, Trump: 810000, 411750
Trump: 202500, 104625
Trump: 3375, 1800
Trump: 360000, 18

NT: 37800, 20160, 
NT: 88200, 47040, 
NT: 441000, 235200, 
NT: 661500, 352800, 
NT: 1323000, 705600, 
NT: 1323000, 705600, 
NT: 1323000, 705600, 
NT: 882000, 470400, 
NT: 441000, 235200, 
NT: 189000, 100800, 
NT: 37800, 20160, 
NT: 9450, 5040, 
NT: 784000, 411600, 
NT: 2352000, 1234800, 
NT: 1568000, 823200, 
NT: 224000, 117600, 
NT: 1568000, 823200, 
NT: 7056000, 3704400, 
NT: 7056000, 3704400, 
NT: 1568000, 823200, 
NT: 672000, 352800, 
NT: 4704000, 2469600, 
NT: 7056000, 3704400, 
NT: 2352000, 1234800, 
NT: 56000, 29400, 
NT: 672000, 352800, 
NT: 1568000, 823200, 
NT: 784000, 411600, 
NT: 4233600, 2152080, 
NT: 35280000, 17934000, 
NT: 70560000, 35868000, 
NT: 42336000, 21520800, 
NT: 7056000, 3586800, 
NT: 201600, 102480, 
NT: 4233600, 2152080, 
NT: 63504000, 32281200, 
NT: 211680000, 107604000, 
NT: 211680000, 107604000, 
NT: 63504000, 32281200, 
NT: 4233600, 2152080, 
NT: 604800, 307440, 
NT: 21168000, 10760400, 
NT: 127008000, 64562400, 
NT: 211680000, 107604000, 
NT: 105840000,

NT: 74088000, 37308600, Trump: 74088000, 37308600
NT: 123480000, 62181000, Trump: 123480000, 62181000
NT: 514500, 264600, Trump: 514500, 264600
NT: 92610000, 46525500, Trump: 92610000, 46525500
NT: 555660000, 279153000, Trump: 555660000, 279153000
NT: 277830000, 139576500, Trump: 277830000, 139576500
NT: 8232000, 4145400, Trump: 8232000, 4145400
NT: 23152500, 11686500, Trump: 23152500, 11686500
NT: 24696000, 12436200, Trump: 24696000, 12436200
NT: 13891500, 7011900, Trump: 13891500, 7011900
NT: 73500, 37800, Trump: 73500, 37800
NT: 771750, 396900, Trump: 771750, 396900
NT: 92610000, 46525500, Trump: 92610000, 46525500
NT: 41160000, 20727000, Trump: 41160000, 20727000
NT: 27783000, 13957650, Trump: 27783000, 13957650
NT: 23152500, 11686500, Trump: 23152500, 11686500
NT: 6945750, 3505950, Trump: 6945750, 3505950
NT: 392000, 197400, Trump: 392000, 197400
NT: 185220000, 31312400, Trump: 185220000, 31312400
NT: 23152500, 11686500, Trump: 23152500, 11686500
NT: 18522000, 9305100, Trump: 1852

NT: 28224, 14196, Trump: 28224, 14196
NT: 59270400, 29705760, Trump: 59270400, 29705760
NT: 9483264, 4769856, Trump: 9483264, 4769856
NT: 526848000, 263894400, Trump: 526848000, 263894400
NT: 263424000, 132182400, Trump: 263424000, 132182400
NT: 1053696, 536256, Trump: 1053696, 536256
NT: 131712000, 66091200, Trump: 131712000, 66091200
NT: 4939200, 2504880, Trump: 4939200, 2504880
NT: 177811200, 89117280, Trump: 177811200, 89117280
NT: 1354752, 681408, Trump: 1354752, 681408
NT: 18816000, 9441600, Trump: 18816000, 9441600
NT: 5268480000, 882789600, Trump: 5268480000, 882789600
NT: 658560000, 330456000, Trump: 658560000, 330456000
NT: 526848000, 263894400, Trump: 526848000, 263894400
NT: 889056000, 445586400, Trump: 889056000, 445586400
NT: 658560000, 330456000, Trump: 658560000, 330456000
NT: 8232000, 4174800, Trump: 8232000, 4174800
NT: 889056000, 445586400, Trump: 889056000, 445586400
NT: 526848000, 263894400, Trump: 526848000, 263894400
NT: 18816000, 9441600, Trump: 18816000, 944160

NT: 1975680000, 989604000, Trump: 1975680000, 989604000
NT: 1111320000, 556983000, Trump: 1111320000, 556983000
NT: 11854080, 5962320, Trump: 11854080, 5962320
NT: 74088000, 37132200, Trump: 74088000, 37132200
NT: 329280000, 164934000, Trump: 329280000, 164934000
NT: 32928000, 16522800, Trump: 32928000, 16522800
NT: 47040, 23940, Trump: 47040, 23940
NT: 493920000, 247842000, Trump: 493920000, 247842000
NT: 82320000, 41307000, Trump: 82320000, 41307000
NT: 1317120, 670320, Trump: 1317120, 670320
NT: 2058000, 1043700, Trump: 2058000, 1043700
NT: 18816000, 9441600, Trump: 18816000, 9441600
NT: 5268480000, 882789600, Trump: 5268480000, 882789600
NT: 889056000, 445586400, Trump: 889056000, 445586400
NT: 889056000, 445586400, Trump: 889056000, 445586400
NT: 526848000, 263894400, Trump: 526848000, 263894400
NT: 526848000, 263894400, Trump: 526848000, 263894400
NT: 18816000, 9441600, Trump: 18816000, 9441600
NT: 658560000, 330456000, Trump: 658560000, 330456000
NT: 658560000, 330456000, Trump:

Trump: 5670, 3780
Trump: 945, 630
Trump: 315, 210
Trump: 630, 420
Trump: 630, 420
Trump: 315, 210
Trump: 504, 336
Trump: 504, 336
Trump: 10584, 7056
Trump: 17640, 11760
Trump: 1512, 1008
Trump: 42336, 24696
Trump: 31752, 21168
Trump: 10584, 7056
Trump: 105840, 70560
Trump: 2520, 1680
Trump: 211680, 123480
Trump: 17640, 11760
Trump: 88200, 58800
Trump: 176400, 117600
Trump: 2520, 1680
Trump: 17640, 11760
Trump: 211680, 123480
Trump: 176400, 117600
Trump: 88200, 58800
Trump: 1512, 1008
Trump: 31752, 21168
Trump: 42336, 24696
Trump: 105840, 70560
Trump: 10584, 7056
Trump: 10584, 7056
Trump: 17640, 11760
Trump: 504, 336
Trump: 504, 336
Trump: 17640, 11760
Trump: 10584, 7056
Trump: 10584, 7056
Trump: 105840, 61740
Trump: 158760, 105840
Trump: 10584, 7056
Trump: 158760, 105840
Trump: 52920, 35280
Trump: 1058400, 617400
Trump: 264600, 176400
Trump: 158760, 105840
Trump: 529200, 352800
Trump: 35280, 23520
Trump: 35280, 23520
Trump: 88200, 58800
Trump: 2116800, 1234800
Trump: 88200, 58800
Trump

Trump: 5040, 2940
Trump: 16800, 10500
Trump: 33600, 21000
Trump: 302400, 163800
Trump: 25200, 14700
Trump: 30240, 16380
Trump: 25200, 14700
Trump: 33600, 21000
Trump: 30240, 16380
Trump: 302400, 163800
Trump: 16800, 10500
Trump: 226800, 132300
Trump: 33600, 21000
Trump: 453600, 245700
Trump: 907200, 491400
Trump: 10080, 6300
Trump: 33600, 21000
Trump: 226800, 132300
Trump: 10080, 6300
Trump: 907200, 491400
Trump: 453600, 245700
Trump: 33600, 21000
Trump: 25200, 14700
Trump: 16800, 10500
Trump: 302400, 163800
Trump: 30240, 16380
Trump: 45360, 26460
Trump: 20160, 12600
Trump: 18144, 9828
Trump: 60480, 32760
Trump: 2016, 1260
Trump: 10080, 6300
Trump: 136080, 79380
Trump: 10080, 6300
Trump: 672, 420
Trump: 90720, 49140
Trump: 90720, 49140
Trump: 672, 420
Trump: 20160, 12600
Trump: 45360, 26460
Trump: 2016, 1260
Trump: 60480, 32760
Trump: 18144, 9828
Trump: 672, 420
Trump: 15120, 8820
Trump: 3360, 2100
Trump: 3360, 2100
Trump: 15120, 8820
Trump: 672, 420
Trump: 96, 60
Trump: 720, 420
Trump

Trump: 147000, 80850
Trump: 19845000, 10253250
Trump: 2940000, 1543500
Trump: 19845000, 10253250
Trump: 39690000, 20506500
Trump: 441000, 242550
Trump: 147000, 80850
Trump: 2940000, 1543500
Trump: 441000, 242550
Trump: 147000, 80850
Trump: 2940000, 1543500
Trump: 19845000, 10253250
Trump: 441000, 242550
Trump: 39690000, 20506500
Trump: 19845000, 10253250
Trump: 441000, 242550
Trump: 2940000, 1543500
Trump: 147000, 80850
Trump: 73500, 40425
Trump: 4410000, 2315250
Trump: 3307500, 1708875
Trump: 1102500, 606375
Trump: 19845000, 10253250
Trump: 1984500, 1025325
Trump: 367500, 202125
Trump: 882000, 463050
Trump: 10500, 5775
Trump: 3675, 2205
Trump: 18375, 11025
Trump: 882000, 463050
Trump: 441000, 242550
Trump: 1984500, 1025325
Trump: 73500, 40425
Trump: 58800, 30870
Trump: 73500, 40425
Trump: 18375, 11025
Trump: 1102500, 569625
Trump: 2940000, 1543500
Trump: 30625, 18375
Trump: 220500, 113925
Trump: 3307500, 1708875
Trump: 367500, 202125
Trump: 588000, 323400
Trump: 17640000, 9114000
Trum

Trump: 9450, 5040
Trump: 4233600, 2152080
Trump: 1058400, 546840
Trump: 23814000, 12039300
Trump: 63504000, 32281200
Trump: 661500, 352800
Trump: 4233600, 2152080
Trump: 63504000, 32281200
Trump: 7056000, 3704400
Trump: 9450, 5040
Trump: 1058400, 546840
Trump: 661500, 352800
Trump: 21168000, 10760400
Trump: 238140000, 120393000
Trump: 105840000, 53802000
Trump: 63504000, 32281200
Trump: 211680000, 107604000
Trump: 7056000, 3704400
Trump: 189000, 100800
Trump: 5292000, 2734200
Trump: 1323000, 705600
Trump: 56000, 29400
Trump: 14112000, 7173600
Trump: 14112000, 7173600
Trump: 35280000, 17934000
Trump: 476280000, 240786000
Trump: 35280000, 17934000
Trump: 1568000, 823200
Trump: 211680000, 107604000
Trump: 211680000, 107604000
Trump: 1568000, 823200
Trump: 882000, 470400
Trump: 8820000, 4557000
Trump: 882000, 470400
Trump: 21168000, 10760400
Trump: 105840000, 53802000
Trump: 238140000, 120393000
Trump: 7056000, 3704400
Trump: 211680000, 107604000
Trump: 63504000, 32281200
Trump: 1323000, 7

Trump: 23152500, 11686500
Trump: 277830000, 139576500
Trump: 6945750, 3505950
Trump: 123480000, 62181000
Trump: 555660000, 279153000
Trump: 24696000, 12436200
Trump: 555660000, 279153000
Trump: 185220000, 93051000
Trump: 24696000, 12436200
Trump: 24696000, 12436200
Trump: 555660000, 279153000
Trump: 123480000, 62181000
Trump: 185220000, 93051000
Trump: 555660000, 279153000
Trump: 24696000, 12436200
Trump: 138915000, 69788250
Trump: 123480000, 62181000
Trump: 771750, 396900
Trump: 277830000, 139576500
Trump: 23152500, 11686500
Trump: 6945750, 3505950
Trump: 5556600, 2791530
Trump: 24696000, 12436200
Trump: 771750, 396900
Trump: 18522000, 9305100
Trump: 13891500, 7011900
Trump: 1389150, 701190
Trump: 257250, 132300
Trump: 13720000, 6909000
Trump: 9261000, 4652550
Trump: 23152500, 11686500
Trump: 92610000, 46525500
Trump: 11576250, 5843250
Trump: 171500, 88200
Trump: 41160000, 20727000
Trump: 92610000, 46525500
Trump: 2744000, 1381800
Trump: 23152500, 11686500
Trump: 555660000, 279153000


NT: 1843968000, 923630400, Trump: 1843968000, 923630400
Trump: 460992000, 231319200
Trump: 311169600, 155955240
NT: 8643600, 4332090, Trump: 8643600, 4332090
NT: 57624000, 28914900, Trump: 57624000, 28914900
NT: 3601500, 1826475, Trump: 3601500, 1826475
NT: 76832000, 38484600, Trump: 76832000, 38484600
NT: 115248000, 57829800, Trump: 115248000, 57829800
Trump: 768320, 391020
NT: 25930800, 12996270, Trump: 25930800, 12996270
Trump: 4148928, 2086812
Trump: 197568, 99372
NT: 2160900, 1095885, Trump: 2160900, 1095885
Trump: 57624000, 28914900
Trump: 25930800, 12996270
NT: 1382976, 368676, Trump: 1382976, 703836
NT: 864360, 452760, 
NT: 197568, 103488, 
NT: 12348, 6468, 
Trump: 345744000, 173489400
Trump: 691488000, 346361400
Trump: 20744640, 10434060
Trump: 388962000, 194944050
Trump: 4148928, 2086812
NT: 3601500, 1826475, Trump: 3601500, 1826475
NT: 288120000, 144574500, Trump: 288120000, 144574500
Trump: 388962000, 194944050
Trump: 8232000, 4130700
NT: 308700, 155820, 
NT: 14817600, 7479

Trump: 3601500, 1826475
NT: 76832000, 38484600, Trump: 76832000, 38484600
NT: 384160000, 192423000, Trump: 384160000, 192423000
NT: 57624000, 28914900, Trump: 57624000, 28914900
NT: 109760, 55860, Trump: 109760, 55860
NT: 1152480000, 577269000, Trump: 1152480000, 577269000
NT: 1296540000, 649813500, Trump: 1296540000, 649813500
NT: 20744640, 10434060, Trump: 20744640, 10434060
NT: 288120000, 144574500, Trump: 288120000, 144574500
NT: 2401000, 1234800, 
NT: 34574400, 8943480, Trump: 34574400, 17390100
NT: 19208000, 9878400, 
NT: 2744000, 1411200, 
NT: 11524800, 5927040, 
NT: 14406000, 7408800, 
NT: 5488000, 2822400, 
NT: 514500, 264600, 
Trump: 768320, 391020
NT: 4148928, 2086812, Trump: 4148928, 2086812
NT: 388962000, 194944050, Trump: 388962000, 194944050
NT: 691488000, 346361400, Trump: 691488000, 346361400
Trump: 25930800, 12996270
NT: 20744640, 10434060, Trump: 20744640, 10434060
NT: 345744000, 173489400, Trump: 345744000, 173489400
Trump: 57624000, 28914900
NT: 1382976, 368676, Tr

Trump: 2520, 1470
Trump: 3780, 2520
Trump: 3780, 2520
Trump: 6048, 4032
Trump: 252, 168
Trump: 1512, 1008
Trump: 2016, 1344
Trump: 2016, 1344
Trump: 6048, 4032
Trump: 18144, 12096
Trump: 40320, 23520
Trump: 10080, 6720
Trump: 30240, 20160
Trump: 40320, 23520
Trump: 30240, 20160
Trump: 10080, 6720
Trump: 6048, 4032
Trump: 18144, 12096
Trump: 2016, 1344
Trump: 2016, 1344
Trump: 1512, 1008
Trump: 252, 168
Trump: 18144, 12096
Trump: 6048, 4032
Trump: 3780, 2520
Trump: 90720, 52920
Trump: 22680, 15120
Trump: 3780, 2520
Trump: 22680, 15120
Trump: 241920, 141120
Trump: 20160, 13440
Trump: 20160, 13440
Trump: 3780, 2520
Trump: 22680, 15120
Trump: 90720, 52920
Trump: 22680, 15120
Trump: 3780, 2520
Trump: 18144, 12096
Trump: 6048, 4032
Trump: 1512, 1008
Trump: 252, 168
Trump: 6048, 4032
Trump: 10080, 6720
Trump: 40320, 23520
Trump: 30240, 20160
Trump: 20160, 13440
Trump: 241920, 141120
Trump: 20160, 13440
Trump: 20160, 13440
Trump: 20160, 13440
Trump: 241920, 141120
Trump: 10080, 6720
Trump: 302

Trump: 21952000, 11015200
Trump: 148176000, 74264400
Trump: 17561600, 8796480
Trump: 13171200, 6609120
Trump: 29635200, 14852880
Trump: 74088000, 37132200
Trump: 148176000, 74264400
Trump: 263424000, 131947200
Trump: 21952000, 11015200
Trump: 790272000, 395841600
Trump: 263424000, 131947200
Trump: 148176000, 74264400
Trump: 21952000, 11015200
Trump: 74088000, 37132200
Trump: 29635200, 14852880
Trump: 17561600, 8796480
Trump: 13171200, 6609120
Trump: 29635200, 14852880
Trump: 158054400, 79168320
Trump: 39513600, 19827360
Trump: 158054400, 79168320
Trump: 29635200, 14852880
Trump: 39513600, 19827360
Trump: 17561600, 8796480
Trump: 29635200, 14852880
Trump: 13171200, 6609120
Trump: 13171200, 6609120
Trump: 13171200, 6609120
Trump: 13171200, 6609120
Trump: 274400, 139160
Trump: 13171200, 6609120
Trump: 1881600, 944160
Trump: 627200, 314720
Trump: 117600, 59640
Trump: 627200, 314720
Trump: 1881600, 944160
Trump: 117600, 59640
Trump: 29400, 14910
Trump: 128, 80
Trump: 2880, 1680
Trump: 640, 

Trump: 150528, 94080
Trump: 3386880, 1975680
Trump: 752640, 470400
Trump: 21504, 13440
Trump: 4064256, 2201472
Trump: 6773760, 3669120
Trump: 150528, 94080
Trump: 752640, 470400
Trump: 3386880, 1975680
Trump: 150528, 94080
Trump: 150528, 94080
Trump: 6773760, 3669120
Trump: 4064256, 2201472
Trump: 21504, 13440
Trump: 501760, 313600
Trump: 564480, 329280
Trump: 150528, 94080
Trump: 2257920, 1223040
Trump: 451584, 244608
Trump: 12544, 7840
Trump: 423360, 246960
Trump: 188160, 117600
Trump: 448, 280
Trump: 112896, 61152
Trump: 282240, 152880
Trump: 12544, 7840
Trump: 150528, 94080
Trump: 1128960, 658560
Trump: 150528, 94080
Trump: 7168, 4480
Trump: 451584, 244608
Trump: 451584, 244608
Trump: 7168, 4480
Trump: 188160, 117600
Trump: 423360, 246960
Trump: 12544, 7840
Trump: 12544, 7840
Trump: 282240, 152880
Trump: 112896, 61152
Trump: 448, 280
Trump: 7168, 4480
Trump: 80640, 47040
Trump: 21504, 13440
Trump: 21504, 13440
Trump: 80640, 47040
Trump: 7168, 4480
Trump: 448, 280
Trump: 2520, 1470


Trump: 5040000, 2604000
Trump: 1512000, 781200
Trump: 26250, 15750
Trump: 105000, 57750
Trump: 26250, 15750
Trump: 2520000, 1323000
Trump: 945000, 488250
Trump: 105000, 57750
Trump: 945000, 488250
Trump: 63000, 32550
Trump: 336000, 184800
Trump: 28000, 16800
Trump: 1512000, 781200
Trump: 1344000, 705600
Trump: 8400, 5040
Trump: 336000, 184800
Trump: 1008000, 554400
Trump: 403200, 211680
Trump: 9072000, 4687200
Trump: 2016000, 1058400
Trump: 1008000, 554400
Trump: 336000, 184800
Trump: 2016000, 1058400
Trump: 9072000, 4687200
Trump: 403200, 211680
Trump: 28000, 16800
Trump: 336000, 184800
Trump: 8400, 5040
Trump: 1344000, 705600
Trump: 1512000, 781200
Trump: 42000, 23100
Trump: 252000, 138600
Trump: 10500, 6300
Trump: 11200, 5880
Trump: 378000, 195300
Trump: 168000, 88200
Trump: 700, 420
Trump: 336000, 184800
Trump: 336000, 184800
Trump: 134400, 70560
Trump: 1008000, 520800
Trump: 134400, 70560
Trump: 10500, 6300
Trump: 252000, 138600
Trump: 42000, 23100
Trump: 700, 420
Trump: 168000, 8

Trump: 352800, 182280
Trump: 441000, 235200
Trump: 21168000, 10760400
Trump: 4704000, 2469600
Trump: 21168000, 10760400
Trump: 441000, 235200
Trump: 352800, 182280
Trump: 50400, 26040
Trump: 189000, 100800
Trump: 1008000, 512400
Trump: 672000, 352800
Trump: 604800, 307440
Trump: 37800, 20160
Trump: 7200, 3720
Trump: 1058400, 546840
Trump: 14112000, 7173600
Trump: 882000, 470400
Trump: 4233600, 2152080
Trump: 1568000, 823200
Trump: 37800, 20160
Trump: 12700800, 6456240
Trump: 3175200, 1640520
Trump: 47628000, 24078600
Trump: 127008000, 64562400
Trump: 1323000, 705600
Trump: 4233600, 2152080
Trump: 63504000, 32281200
Trump: 7056000, 3704400
Trump: 63504000, 32281200
Trump: 476280000, 240786000
Trump: 211680000, 107604000
Trump: 63504000, 32281200
Trump: 211680000, 107604000
Trump: 7056000, 3704400
Trump: 224000, 117600
Trump: 42336000, 21520800
Trump: 42336000, 21520800
Trump: 70560000, 35868000
Trump: 952560000, 481572000
Trump: 70560000, 35868000
Trump: 1568000, 823200
Trump: 211680000

Trump: 889056000, 445586400
Trump: 2058000, 1043700
Trump: 493920000, 247842000
Trump: 1111320000, 556983000
Trump: 32928000, 16522800
Trump: 493920000, 247842000
Trump: 11854080000, 5937624000
Trump: 1975680000, 989604000
Trump: 1111320000, 556983000
Trump: 1975680000, 989604000
Trump: 32928000, 16522800
Trump: 263424000, 132182400
Trump: 1975680000, 990192000
Trump: 263424000, 132182400
Trump: 10536960000, 5277888000
Trump: 10536960000, 5277888000
Trump: 5268480000, 2638944000
Trump: 32928000, 16522800
Trump: 1111320000, 556983000
Trump: 493920000, 247842000
Trump: 2058000, 1043700
Trump: 1975680000, 989604000
Trump: 11854080000, 5937624000
Trump: 493920000, 247842000
Trump: 1975680000, 989604000
Trump: 1111320000, 556983000
Trump: 32928000, 16522800
Trump: 177811200, 89117280
Trump: 263424000, 132182400
Trump: 4939200, 2504880
Trump: 3161088000, 1583366400
Trump: 790272000, 396547200
Trump: 889056000, 445586400
Trump: 4939200, 2475480
Trump: 32928000, 16522800
Trump: 2058000, 104370

Trump: 4939200, 2493120
Trump: 103723200, 52355520
Trump: 138297600, 69478080
Trump: 19208000, 9878400
Trump: 614656000, 309523200
Trump: 138297600, 69478080
Trump: 19208000, 9878400
Trump: 103723200, 52355520
Trump: 4939200, 2493120
Trump: 112896, 57792
Trump: 197568, 103488
Trump: 14817600, 7479360
Trump: 5488000, 2822400
Trump: 43904000, 22108800
Trump: 2744000, 1411200
Trump: 4939200, 2493120
Trump: 12348, 6468
Trump: 8643600, 4362960
Trump: 1382976, 707952
Trump: 86436000, 43423800
Trump: 129654000, 65444400
Trump: 864360, 452760
Trump: 34574400, 17369520
Trump: 230496000, 116071200
Trump: 14406000, 7408800
Trump: 308700, 155820
Trump: 8643600, 4362960
Trump: 2401000, 1234800
Trump: 103723200, 52355520
Trump: 2074464000, 1042171200
Trump: 518616000, 261777600
Trump: 1244678400, 625302720
Trump: 1843968000, 928569600
Trump: 34574400, 17781120
Trump: 14817600, 7479360
Trump: 103723200, 52355520
Trump: 11524800, 5927040
Trump: 514500, 264600
Trump: 230496000, 116071200
Trump: 1296540

In [49]:
results_nt

array([           13,           555,         19996,        631959,
            16350012,     341718684,    5611979988,   68565702195,
        567603793650, 2605624201677])

In [50]:
results_nt_reduced

array([           13,           534,         19560,        609351,
            15878664,     329258634,    5399087904,   65133903240,
        531909059940, 2313743264616])

In [51]:
results_trump

array([           15,          1098,         55062,       1974972,
            56321424,    1251390792,   21311636496,  265235061420,
       2198253354300, 9803165865276])

In [52]:
results_trump_reduced

array([           15,          1092,         54486,       1947030,
            55464768,    1230253212,   20907953328,  258840541440,
       2127227461980, 9253316793504])

In [53]:
results_nt.sum(), results_trump.sum()

(3247764398729, 12289275660855)

In [54]:
results_nt_reduced.sum(), results_trump_reduced.sum()

(2916531082456, 11661580470855)

In [55]:
nt_count

array([    5,    59,   389,  1921,  6806, 17825, 33053, 41650, 31428,
       10701], dtype=int32)

In [56]:
trump_count

array([     9,    158,   1272,   6801,  25509,  68760, 129969, 164893,
       124563,  42084], dtype=int32)